// EMPLOYEES
export const ADD_EMPLOYEE = 'ADD_EMPLOYEE';
export const UPDATE_EMPLOYEE = 'UPDATE_EMPLOYEE';
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';
export const CURRENT_EMPLOYEE = 'CURRENT_EMPLOYEE';

// UI
export const UPDATE_PAGE = 'UPDATE_PAGE';
export const UPDATE_DEFAULT_VIEW = 'UPDATE_DEFAULT_VIEW';
